image: python:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: "test"
  DATABASE_URL: "postgresql://test:test@postgres:5432/test"
  ENV_FOR_DYNACONF: testing_gitlab_ci

before_script:
  - python -V
  - pip install pipenv
  - pipenv --python $(which python) install --dev

stages:
  - test
  - build
  - deploy

.test-generic:
  script:
    - ./qa.sh

test-latest:
  extends: .test-generic
  stage: test
  image: python:latest

test-3.7:
  extends: .test-generic
  stage: test
  image: python:3.7

test-3.6:
  extends: .test-generic
  stage: test
  image: python:3.6

build wheels:
  stage: build
  when: on_success
  script:
    - pipenv run python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/

distribute:
  stage: deploy
  when: on_success
  only:
    - releases@tgrx/bulky
  script:
    - pipenv run twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
