image: python:latest

services:
  - postgres:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: "test"
  DATABASE_URL: "postgresql://test:test@postgres:5432/test"

cache:
  paths:
    - .cache/pip
    - venv

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install --upgrade --requirement requirements.txt

test:
  script:
  - python setup.py test

run:
  script:
  - python setup.py sdist
