language: python
python:
  - "3.7-dev"

services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  - DATABASE_URL="postgresql://postgres@localhost:5432/travis_ci_test"

install:
  - easy_install -U pip
  - pip install pipenv
  - pipenv install --dev

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - ./qa.sh
