language: python
python:
  - "3.7-dev"

services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  - PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache
  - DATABASE_URL="postgresql://postgres@localhost:5432/travis_ci_test"

install:
  - easy_install -U pip
  - pip install --upgrade --requirement requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python -m unittest
